- hosts: local
  gather_facts: False
  vars:
    pacotes:
      - sysstat
      - docker
      - nginx

  tasks:
  - name: Exibindo variaveis
    debug: 
      msg: "{{ item }}"
    loop:
      - nginx
      - docker
      - sysstat
