version: "3"
services:
  impacta_app:
    image: ${name_var}
    container_name: impacta_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - REDIS=redis
  redis:
    image: "redis:alpine"
